# Default values for mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
terminationGracePeriodSeconds: 10
image:
  registry: paulb314
  name: uploader-app
  tag: latest
resources:
  cpu: 0.5
  memory: 300Mi

service:
  port: 3000
  ingressPort: 443
  loadBalancerIP: "35.187.179.96"

ports:
  logstash: 31998

volume:
  accessMode: ReadWriteOnce
  storageRequest: 5Gi
  volumeMode: standard

domain: quelle-indignite.com


ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  global_static_ip_name: uploader-ip
  hosts:
    - host: uploader-app.polo.localhost
      paths:
        - path: /
          pathType: Prefix
          port: 3000
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
