apiVersion: v1
kind: Service
metadata:
  name: uploader-app
  namespace: polo
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  {{- with .Values.service }}
  selector:
    app: {{ .name }}
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- end }}
  