# mongoDB connection parameters
mongo:
    host: db
    port: 27017
    user: dqrk
    pass: dqrk
    # database name
    db: uploader
    # optional authentication database 
    authdb:

# uploaded files storage path
# can be absolute or relative to node process working directory
upload:
    # temporary uploads directory
    tmp_path: /tmp/uploader
    # final storage directory
    storage_path: uploaded

# cookie session configuration
session:
    # secret : must be changed
    secret: Lk2z9J77LqMfLQI88d7UVVyga/0
