# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  namespace: polo
  project_id: terraform-test-319307
  location: "europe-west1"
  hostIp: 34.142.1.110
  hostname: quelle-indignite.com
  
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  global_static_ip_name: quelleindignite
  # kibana:

secrets:
  mongo:
    AUTH_PART_MONGO: YWRtaW4=
    MONGO_INITDB_DATABASE: dXBsb2FkZXI=
    MONGO_INITDB_ROOT_PASSWORD: YWljMVV5b2g0dnVhMWll
    MONGO_INITDB_ROOT_USERNAME: cm9vdA==

app:
  replicas: 1
  hostname: uploader.quelle-indignite.com
  service:
    name: uploader-app
    port: 3000
    ingressPort: 443
    loadBalancerIP: "34.142.1.110"


eck:
  version: 7.13.4
  elasticsearch:
    port: 9200
    host: elasticsearch.quelle-indignite.com
    protocol: "http"
    secrets:
      username: YWRtaW4tdGVzdAo= #admin-test
      password: cGFzc3dvcmQtdGVzdAo= #password-test
    resources:
      requests:
        memory: 4Gi
        cpu: 1
      limits:
        memory: 4Gi
        cpu: 1
  kibana:
    service:
      name: devops-chart-kibana
      port: 5601
    host: "kibana.quelle-indignite.com"