apiVersion: v1
kind: Service
metadata:
  labels:
    name: elasticsearch
  name: elasticsearch
spec:
  selector:
    name: elasticsearch
  type: NodePort
  ports:
    - nodePort: {{ .Values.ports.elasticsearch }}
      port: 9200
      protocol: TCP
      targetPort: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    name: kibana
spec:
  selector:
    name: kibana
  type: NodePort
  ports:
    - nodePort: {{ .Values.ports.kibana }}
      port: 5601
      protocol: TCP
      targetPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    name: logstash
spec:
  selector:
    name: logstash
  type: NodePort
  ports:
  - nodePort: {{ .Values.ports.logstash }}
    port: 5044
    protocol: TCP
    targetPort: 5044