apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  namespace: {{.Values.global.namespace}}
spec:
  {{- with .Values.volume}}
  accessModes:
    - {{.accessMode}}
  resources:
    requests:
      storage: {{.storageRequest}}
  {{- end}}
