apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{.Values.global.namespace}}
spec:
  {{- with .Values.service}}
  type: {{.type}}
  ports:
  - targetPort: {{.port}}
    port: {{.port}}
  {{- end}}
  selector:
    app: mongodb