apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
  namespace: {{.Values.global.namespace}}
spec:
  selector:
    matchLabels:
      app: mongodb # has to match .spec.template.metadata.labels
  serviceName: mongodb
  replicas: {{.Values.replicaCount}}
  updateStrategy:
        type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: {{.Values.terminationGracePeriodSeconds}}
      containers:
      - name: mongodb
        {{- with .Values.image}}
        image: "{{.name}}:{{.tag}}"
        {{- end }}
        {{- with .Values.resources }}
        resources:
          limits:
            cpu: {{ .cpu }}
            memory: {{.memory}}
          requests:
            cpu: {{ .cpu }}
            memory: {{.memory}}
        {{- end }}
        envFrom:
        - secretRef:
            name: mongo-secret
        ports:
        - containerPort: {{.Values.service.port}}
          name: mongo
        volumeMounts:
          - name: data
            mountPath: "/data/db"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongo-claim