---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: uploader-app
  labels:
    app: uploader
  namespace: {{.Values.global.namespace}}
spec:
  replicas: 1  #  {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: uploader-app
  strategy: {}
  template:
    metadata:
      labels:
        app: uploader-app
    spec:
      containers:
      {{- with .Values.image }}
      - image: "{{ $.Values.image.registry }}/{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
      {{- end }}
        name: uploader-app
        command: ["yarn"]
        args: ["start-prod"]
        ports:
          {{- with .Values.service }}
          - containerPort: {{ $.Values.service.port  }}
          {{- end }}
        resources:
          {{- with .Values.resources }}
          limits:
            {{- toYaml $.Values.resources | nindent 12 }}
          requests:
            {{- toYaml $.Values.resources | nindent 12 }}
          {{- end}}
        volumeMounts:
          - name: uploaded
            mountPath: /usr/app/src/uploaded
        envFrom:
        - secretRef:
            name: mongo-secret
      - name: filebeat
         image: elastic/filebeat:7.8.0
         env:
         - name: LOGSTASH_HOSTS
           value: "{{ .Values.global.hostIp }}:{{ .Values.ports.logstash }}"
         args: [
           "-c", "/etc/filebeat/filebeat.yml",
           "-e"
         ]
         volumeMounts:
         - name: log-output
           mountPath: /tmp/
         - name: beat-config
           mountPath: /etc/filebeat/
      volumes:
      - name: uploaded
        persistentVolumeClaim:
          claimName: uploads-claim
      - name: log-output
         emptyDir: {}
      - name: beat-config
         configMap:
           name: beat-config
           items:
           - key: filebeat.yml
             path: filebeat.yml