---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: uploader-app
  labels:
    app: uploader
  namespace: polo  #  {{.Values.global.namespace}}
spec:
  replicas: 1  #  {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: uploader-app
  strategy: {}
  template:
    metadata:
      labels:
        app: uploader-app
    spec:
      containers:
      {{- with .Values.image }}
      - image: "{{ $.Values.image.registry }}/{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
      {{- end }}
        name: uploader-app
        command: ["yarn"]
        args: ["start-prod"]
        ports:
          {{- with .Values.service }}
          - containerPort: {{ $.Values.service.port  }}
          {{- end }}
        resources:
          {{- with .Values.resources }}
          limits:
            {{- toYaml $.Values.resources | nindent 12 }}
          requests:
            {{- toYaml $.Values.resources | nindent 12 }}
          {{- end}}
        volumeMounts:
          - name: uploaded
            mountPath: /usr/app/src/uploaded
        envFrom:
        - secretRef:
            name: mongo-secret
      volumes:
      - name: uploaded
        persistentVolumeClaim:
          claimName: uploads-claim
