apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-uploader-app
  namespace: {{ .Values.global.namespace}}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{.Values.ingress.global_static_ip_name}}
    networking.gke.io/managed-certificates: uploader-certificate
spec:
  rules: 
    - host: {{ .Values.global.hostname }}
      http:
        paths:
        - path: /*
          pathType: Prefix
          backend:
            service:
              name: uploader-app
              port:
                number: {{ .Values.service.port }}
      