apiVersion: v1
kind: Service
metadata:
  name: uploader-app
  namespace: polo
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: uploader-app
  type: NodePort
  {{- with .Values.service }}
  ports:
  - name: http
    protocol: TCP
    port: {{ $.Values.service.port }}
    targetPort: {{ $.Values.service.port }}
  {{- end }}
  