apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: mongo-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/home/k8s-data/devops-test/mongo"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploader-pv
spec:
  storageClassName: uploader-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/home/k8s-data/devops-test/uploader"