apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: local
spec:
  storageClassName: mongo-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/home/k8s-data/devops-test/mongo"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
  labels:
    type: local
spec:
  storageClassName: uploads-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/home/k8s-data/devops-test/uploads"

