apiVersion: v1
data:
  AUTH_PART_MONGO: YWRtaW4=
  MONGO_INITDB_DATABASE: dXBsb2FkZXI=
  MONGO_INITDB_ROOT_PASSWORD: YWljMVV5b2g0dnVhMWll
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo-secret
