apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  namespace: polo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: mongo-pv
  # selector:
  #   matchLabels:
  #     type: local

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
  namespace: polo
spec:
  selector:
    matchLabels:
      app: mongodb # has to match .spec.template.metadata.labels
  serviceName: mongodb
  replicas: 1 # by default is 1
  updateStrategy:
        type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: "mongo:4.4.0"
        resources:
          limits:
            cpu: "1"
            memory: "300Mi"
          requests:
            cpu: "1"
            memory: "300Mi"
        envFrom:
        - secretRef:
            name: mongo-secret
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
          - name: data
            mountPath: "/data/db"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongo-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: polo
spec:
  type: ClusterIP
  ports:
  - targetPort: 27017
    port: 27017
  selector:
    app: mongodb